/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Patient;

import view.Admin.HospitalAdmin.*;
import view.Admin.AdminJFrame;
import view.MainJFrame;

/**
 *
 * @author karan
 */
public class PatientView extends javax.swing.JFrame {

    /**
     * Creates new form PatientView
     */
    public PatientView() {
        initComponents();
        workArea.setSize(900, 900);
        setLocationRelativeTo(null);
        PatientDetails hospitalView = new PatientDetails();
        splitPane.setRightComponent(hospitalView);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btn_back_admin1 = new javax.swing.JButton();
        btn_hospitals1 = new javax.swing.JButton();
        btn_patients1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setPreferredSize(new java.awt.Dimension(900, 800));

        controlPanel.setBackground(new java.awt.Color(153, 255, 204));

        btn_back_admin1.setBackground(new java.awt.Color(255, 255, 255));
        btn_back_admin1.setForeground(new java.awt.Color(51, 51, 255));
        btn_back_admin1.setText("<- Logout");
        btn_back_admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_admin1ActionPerformed(evt);
            }
        });

        btn_hospitals1.setBackground(new java.awt.Color(255, 255, 255));
        btn_hospitals1.setForeground(new java.awt.Color(51, 51, 255));
        btn_hospitals1.setText("Details");
        btn_hospitals1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hospitals1ActionPerformed(evt);
            }
        });

        btn_patients1.setBackground(new java.awt.Color(255, 255, 255));
        btn_patients1.setForeground(new java.awt.Color(51, 51, 255));
        btn_patients1.setText("Appointment");
        btn_patients1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patients1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back_admin1)
                    .addComponent(btn_hospitals1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_patients1)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_back_admin1)
                .addGap(124, 124, 124)
                .addComponent(btn_hospitals1)
                .addGap(18, 18, 18)
                .addComponent(btn_patients1)
                .addContainerGap(759, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1385, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back_admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_admin1ActionPerformed
        MainJFrame.loginSession.setObject(null);

        this.dispose();
        new MainJFrame().setVisible(true);
    }//GEN-LAST:event_btn_back_admin1ActionPerformed

    private void btn_hospitals1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hospitals1ActionPerformed
        HospitalViewUpdate h = new HospitalViewUpdate();
        splitPane.setRightComponent(h);
    }//GEN-LAST:event_btn_hospitals1ActionPerformed

    private void btn_patients1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patients1ActionPerformed
        PatientViewUpdate d = new PatientViewUpdate();
        splitPane.setRightComponent(d);
    }//GEN-LAST:event_btn_patients1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientView().setVisible(true);
            }
        });
    }
    
    
    public void setHospitalCreateView() {                                               
        // TODO add your handling code here:
        HospitalCreate createPanel = new HospitalCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setDoctorCreateView() {                                               
        // TODO add your handling code here:
        DoctorCreate createPanel = new DoctorCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setEncounterCreateView() {                                               
        // TODO add your handling code here:
        EncounterCreate createPanel = new EncounterCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setPatientCreateView() {                                               
        // TODO add your handling code here:
        PatientCreate createPanel = new PatientCreate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setEncounterUpdateView() {                                               
        // TODO add your handling code here:
        EncounterViewUpdate createPanel = new EncounterViewUpdate();
        splitPane.setRightComponent(createPanel);
    }
    
    public void setDoctorUpdateView() {                                               
        
        DoctorViewUpdate createPanel = new DoctorViewUpdate();
        splitPane.setRightComponent(createPanel);
    }
    public void setPatientUpdateView() {                                               
        
        PatientViewUpdate createPanel = new PatientViewUpdate();
        splitPane.setRightComponent(createPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back_admin1;
    private javax.swing.JButton btn_hospitals1;
    private javax.swing.JButton btn_patients1;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}

